### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ip' since distributed v1.16

### ISSUE THREAD

**Issue by dkmichaels** [mfouesneau/dasksge#4]
I get the following exception:

In [5]: sge = GridEngineScheduler()
In [6]: sge.start_pool(3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-871567768fcb> in <module>()
----> 1 sge.start_pool(3)

src/main/pyenv/local/lib/python2.7/site-packages/dasksge-0.1-py2.7.egg/dasksge/dasksge.pyc in start_pool(self, n, **kwargs)
    295             number of workers to put in the queue
    296         """
--> 297         self.start_dask_scheduler(**kwargs)
    298         self._schedule(n)
    299

src/main/pyenv/local/lib/python2.7/site-packages/dasksge-0.1-py2.7.egg/dasksge/dasksge.pyc in start_dask_scheduler(self, **kwargs)
    280         if self.cluster is not None:
    281             self.cluster.close()
--> 282         self.cluster = _Cluster(**kwargs)
    283
    284     def killall(self, verbose=False):

src/main/pyenv/local/lib/python2.7/site-packages/dasksge-0.1-py2.7.egg/dasksge/dasksge.pyc in __init__(self, n_workers, threads_per_worker, nanny, loop, start, scheduler_port, scheduler_ip, silence_logs, diagnostics_port, services, **kwargs)
    115
    116         self.scheduler = distributed.Scheduler(loop=self.loop, ip=HOSTIP,
--> 117                                                services=services)
    118         self.scheduler.start(scheduler_port)
    119         self.workers = []

src/main/pyenv/local/lib/python2.7/site-packages/distributed/scheduler.pyc in __init__(self, center, loop, delete_interval, synchronize_worker_interval, services, allowed_failures, extensions, validate, scheduler_file, **kwargs)
    342         super(Scheduler, self).__init__(
    343             handlers=self.handlers, io_loop=self.loop,
--> 344             connection_limit=connection_limit, deserialize=False, **kwargs)
    345
    346         for ext in extensions:

TypeError: __init__() got an unexpected keyword argument 'ip'

It appears v.1.16 of distributed changed the constructor substantially, ip is no longer an argument.

**Comment by mfouesneau** [comment]
Yes distributed has gone through a deep refactoring and all the API has changed.

Check https://github.com/dask/dask-drmaa, hopefully it gets the upgrades.
